import { FoodItemTACO } from "./types";

export const TACO_DATABASE: FoodItemTACO[] = [
  // --- CARNES & OVOS ---
  {
    id: "taco-1",
    nome: "Peito de Frango sem pele, grelhado",
    categoria: "Carnes & Ovos",
    porcaoPadraoGramas: 100,
    calorias: 159,
    proteinas: 32.0,
    carboidratos: 0.0,
    gorduras: 2.5,
    fibras: 0.0,
    medidasCaseiras: [
      { descricao: "1 filé médio", gramas: 120 },
      { descricao: "1 filé grande", gramas: 150 },
      { descricao: "1 colher de sopa picado", gramas: 25 },
      { descricao: "Porção de 100g", gramas: 100 },
    ],
  },
  {
    id: "taco-2",
    nome: "Ovo de Galinha, inteiro, cozido",
    categoria: "Carnes & Ovos",
    porcaoPadraoGramas: 100,
    calorias: 146,
    proteinas: 13.3,
    carboidratos: 0.6,
    gorduras: 9.5,
    fibras: 0.0,
    medidasCaseiras: [
      { descricao: "1 unidade média", gramas: 50 },
      { descricao: "2 unidades médias", gramas: 100 },
      { descricao: "3 unidades médias", gramas: 150 },
    ],
  },
  {
    id: "taco-3",
    nome: "Clara de Ovo de Galinha, cozida",
    categoria: "Carnes & Ovos",
    porcaoPadraoGramas: 100,
    calorias: 48,
    proteinas: 11.2,
    carboidratos: 0.0,
    gorduras: 0.2,
    fibras: 0.0,
    medidasCaseiras: [
      { descricao: "1 clara média", gramas: 33 },
      { descricao: "3 claras médias", gramas: 100 },
      { descricao: "1 xícara de claras", gramas: 240 },
    ],
  },
  {
    id: "taco-4",
    nome: "Carne Bovina (Patinho), sem gordura, grelhado/moído",
    categoria: "Carnes & Ovos",
    porcaoPadraoGramas: 100,
    calorias: 219,
    proteinas: 35.9,
    carboidratos: 0.0,
    gorduras: 7.3,
    fibras: 0.0,
    medidasCaseiras: [
      { descricao: "1 bife médio", gramas: 120 },
      { descricao: "1 colher de sopa cheia (moído)", gramas: 30 },
      { descricao: "4 colheres de sopa cheias", gramas: 120 },
      { descricao: "Porção de 150g", gramas: 150 },
    ],
  },
  {
    id: "taco-5",
    nome: "Filé de Tilápia, grelhado",
    categoria: "Carnes & Ovos",
    porcaoPadraoGramas: 100,
    calorias: 128,
    proteinas: 26.2,
    carboidratos: 0.0,
    gorduras: 2.7,
    fibras: 0.0,
    medidasCaseiras: [
      { descricao: "1 filé médio", gramas: 130 },
      { descricao: "1 filé grande", gramas: 180 },
    ],
  },
  {
    id: "taco-6",
    nome: "Salmão sem pele, fresco, grelhado",
    categoria: "Carnes & Ovos",
    porcaoPadraoGramas: 100,
    calorias: 242,
    proteinas: 26.1,
    carboidratos: 0.0,
    gorduras: 14.5,
    fibras: 0.0,
    medidasCaseiras: [
      { descricao: "1 posta média", gramas: 140 },
      { descricao: "1 filé grande", gramas: 200 },
    ],
  },
  {
    id: "taco-7",
    nome: "Atum em conserva em água (sólido/ralado)",
    categoria: "Carnes & Ovos",
    porcaoPadraoGramas: 100,
    calorias: 116,
    proteinas: 26.0,
    carboidratos: 0.0,
    gorduras: 0.8,
    fibras: 0.0,
    medidasCaseiras: [
      { descricao: "1 lata drenada", gramas: 120 },
      { descricao: "1/2 lata drenada", gramas: 60 },
      { descricao: "1 colher de sopa", gramas: 20 },
    ],
  },

  // --- CEREAIS & LEGUMINOSAS ---
  {
    id: "taco-8",
    nome: "Arroz Branco, tipo 1, cozido",
    categoria: "Cereais & Leguminosas",
    porcaoPadraoGramas: 100,
    calorias: 128,
    proteinas: 2.5,
    carboidratos: 28.1,
    gorduras: 0.2,
    fibras: 1.6,
    medidasCaseiras: [
      { descricao: "1 colher de sopa cheia", gramas: 25 },
      { descricao: "1 escumadeira rasa", gramas: 100 },
      { descricao: "1 escumadeira cheia", gramas: 150 },
      { descricao: "1 xícara de chá cheia", gramas: 160 },
    ],
  },
  {
    id: "taco-9",
    nome: "Arroz Integral, cozido",
    categoria: "Cereais & Leguminosas",
    porcaoPadraoGramas: 100,
    calorias: 124,
    proteinas: 2.6,
    carboidratos: 25.8,
    gorduras: 1.0,
    fibras: 2.7,
    medidasCaseiras: [
      { descricao: "1 colher de sopa cheia", gramas: 25 },
      { descricao: "1 escumadeira cheia", gramas: 140 },
    ],
  },
  {
    id: "taco-10",
    nome: "Feijão Carioca, cozido (grão + caldo)",
    categoria: "Cereais & Leguminosas",
    porcaoPadraoGramas: 100,
    calorias: 76,
    proteinas: 4.8,
    carboidratos: 13.6,
    gorduras: 0.5,
    fibras: 8.5,
    medidasCaseiras: [
      { descricao: "1 concha média", gramas: 130 },
      { descricao: "1 concha grande", gramas: 180 },
      { descricao: "1 colher de sopa cheia de grãos", gramas: 20 },
    ],
  },
  {
    id: "taco-11",
    nome: "Feijão Preto, cozido",
    categoria: "Cereais & Leguminosas",
    porcaoPadraoGramas: 100,
    calorias: 77,
    proteinas: 4.5,
    carboidratos: 14.0,
    gorduras: 0.5,
    fibras: 8.4,
    medidasCaseiras: [
      { descricao: "1 concha média", gramas: 130 },
      { descricao: "1 concha grande", gramas: 180 },
    ],
  },
  {
    id: "taco-12",
    nome: "Aveia em Flocos / Farelo de Aveia",
    categoria: "Cereais & Leguminosas",
    porcaoPadraoGramas: 100,
    calorias: 394,
    proteinas: 13.9,
    carboidratos: 66.6,
    gorduras: 8.5,
    fibras: 9.1,
    medidasCaseiras: [
      { descricao: "1 colher de sopa cheia", gramas: 15 },
      { descricao: "2 colheres de sopa cheias", gramas: 30 },
      { descricao: "1 xícara de chá", gramas: 80 },
    ],
  },
  {
    id: "taco-13",
    nome: "Batata Doce, cozida com casca",
    categoria: "Cereais & Leguminosas",
    porcaoPadraoGramas: 100,
    calorias: 77,
    proteinas: 0.6,
    carboidratos: 18.4,
    gorduras: 0.1,
    fibras: 2.2,
    medidasCaseiras: [
      { descricao: "1 unidade pequena", gramas: 100 },
      { descricao: "1 unidade média", gramas: 160 },
      { descricao: "3 fatias médias", gramas: 120 },
    ],
  },
  {
    id: "taco-14",
    nome: "Batata Inglesa, cozida",
    categoria: "Cereais & Leguminosas",
    porcaoPadraoGramas: 100,
    calorias: 52,
    proteinas: 1.2,
    carboidratos: 11.9,
    gorduras: 0.0,
    fibras: 1.3,
    medidasCaseiras: [
      { descricao: "1 unidade média", gramas: 140 },
      { descricao: "1 colher de sopa de purê", gramas: 35 },
    ],
  },
  {
    id: "taco-15",
    nome: "Mandioca / Aipim, cozido",
    categoria: "Cereais & Leguminosas",
    porcaoPadraoGramas: 100,
    calorias: 125,
    proteinas: 0.6,
    carboidratos: 30.1,
    gorduras: 0.3,
    fibras: 1.6,
    medidasCaseiras: [
      { descricao: "1 pedaço médio", gramas: 100 },
      { descricao: "2 pedaços médios", gramas: 200 },
    ],
  },
  {
    id: "taco-16",
    nome: "Pão de Forma Integral (100% integral)",
    categoria: "Cereais & Leguminosas",
    porcaoPadraoGramas: 100,
    calorias: 253,
    proteinas: 9.4,
    carboidratos: 49.9,
    gorduras: 2.5,
    fibras: 6.9,
    medidasCaseiras: [
      { descricao: "1 fatia", gramas: 25 },
      { descricao: "2 fatias", gramas: 50 },
    ],
  },
  {
    id: "taco-17",
    nome: "Goma de Mandioca Hidratada para Tapioca",
    categoria: "Cereais & Leguminosas",
    porcaoPadraoGramas: 100,
    calorias: 240,
    proteinas: 0.0,
    carboidratos: 60.0,
    gorduras: 0.0,
    fibras: 0.5,
    medidasCaseiras: [
      { descricao: "2 colheres de sopa rasas", gramas: 40 },
      { descricao: "3 colheres de sopa cheias", gramas: 60 },
      { descricao: "1 disco médio", gramas: 70 },
    ],
  },

  // --- FRUTAS & SUCOS ---
  {
    id: "taco-18",
    nome: "Banana Prata, crua",
    categoria: "Frutas & Sucos",
    porcaoPadraoGramas: 100,
    calorias: 98,
    proteinas: 1.3,
    carboidratos: 26.0,
    gorduras: 0.1,
    fibras: 2.0,
    medidasCaseiras: [
      { descricao: "1 unidade média", gramas: 70 },
      { descricao: "1 unidade grande", gramas: 100 },
    ],
  },
  {
    id: "taco-19",
    nome: "Maçã Fuji, com casca, fresca",
    categoria: "Frutas & Sucos",
    porcaoPadraoGramas: 100,
    calorias: 56,
    proteinas: 0.3,
    carboidratos: 15.2,
    gorduras: 0.2,
    fibras: 1.3,
    medidasCaseiras: [
      { descricao: "1 unidade média", gramas: 130 },
      { descricao: "1 unidade grande", gramas: 180 },
    ],
  },
  {
    id: "taco-20",
    nome: "Morango, cru",
    categoria: "Frutas & Sucos",
    porcaoPadraoGramas: 100,
    calorias: 30,
    proteinas: 0.9,
    carboidratos: 6.8,
    gorduras: 0.3,
    fibras: 1.7,
    medidasCaseiras: [
      { descricao: "5 unidades médias", gramas: 75 },
      { descricao: "1 xícara cheia", gramas: 150 },
    ],
  },
  {
    id: "taco-21",
    nome: "Mamão Papaia, cru",
    categoria: "Frutas & Sucos",
    porcaoPadraoGramas: 100,
    calorias: 40,
    proteinas: 0.5,
    carboidratos: 10.4,
    gorduras: 0.1,
    fibras: 1.0,
    medidasCaseiras: [
      { descricao: "1/2 unidade pequena", gramas: 140 },
      { descricao: "1 fatia média", gramas: 100 },
    ],
  },
  {
    id: "taco-22",
    nome: "Abacate, fresco",
    categoria: "Frutas & Sucos",
    porcaoPadraoGramas: 100,
    calorias: 96,
    proteinas: 1.2,
    carboidratos: 6.0,
    gorduras: 8.4,
    fibras: 6.3,
    medidasCaseiras: [
      { descricao: "2 colheres de sopa cheias", gramas: 50 },
      { descricao: "1/4 de unidade", gramas: 100 },
    ],
  },
  {
    id: "taco-23",
    nome: "Uva Passa / Thompson",
    categoria: "Frutas & Sucos",
    porcaoPadraoGramas: 100,
    calorias: 299,
    proteinas: 3.1,
    carboidratos: 79.2,
    gorduras: 0.5,
    fibras: 3.7,
    medidasCaseiras: [
      { descricao: "1 colher de sopa", gramas: 15 },
      { descricao: "1 punhado", gramas: 30 },
    ],
  },

  // --- LATICÍNIOS ---
  {
    id: "taco-24",
    nome: "Iogurte Natural Desnatado",
    categoria: "Laticínios",
    porcaoPadraoGramas: 100,
    calorias: 41,
    proteinas: 3.8,
    carboidratos: 5.8,
    gorduras: 0.3,
    fibras: 0.0,
    medidasCaseiras: [
      { descricao: "1 pote comercial", gramas: 170 },
      { descricao: "1 copo médio", gramas: 200 },
    ],
  },
  {
    id: "taco-25",
    nome: "Queijo Minas Frescal",
    categoria: "Laticínios",
    porcaoPadraoGramas: 100,
    calorias: 264,
    proteinas: 17.4,
    carboidratos: 3.2,
    gorduras: 20.2,
    fibras: 0.0,
    medidasCaseiras: [
      { descricao: "1 fatia média", gramas: 30 },
      { descricao: "2 fatias médias", gramas: 60 },
    ],
  },
  {
    id: "taco-26",
    nome: "Queijo Cottage (0% a 2% gordura)",
    categoria: "Laticínios",
    porcaoPadraoGramas: 100,
    calorias: 98,
    proteinas: 12.5,
    carboidratos: 3.4,
    gorduras: 4.3,
    fibras: 0.0,
    medidasCaseiras: [
      { descricao: "1 colher de sopa cheia", gramas: 30 },
      { descricao: "2 colheres de sopa cheias", gramas: 60 },
      { descricao: "1 pote pequeno", gramas: 150 },
    ],
  },
  {
    id: "taco-27",
    nome: "Leite de Vaca Desnatado",
    categoria: "Laticínios",
    porcaoPadraoGramas: 100,
    calorias: 35,
    proteinas: 3.4,
    carboidratos: 5.0,
    gorduras: 0.1,
    fibras: 0.0,
    medidasCaseiras: [
      { descricao: "1 xícara de chá", gramas: 200 },
      { descricao: "1 copo grande", gramas: 250 },
    ],
  },

  // --- GORDURAS & ÓLEOS ---
  {
    id: "taco-28",
    nome: "Azeite de Oliva Extravirgem",
    categoria: "Gorduras & Óleos",
    porcaoPadraoGramas: 100,
    calorias: 884,
    proteinas: 0.0,
    carboidratos: 0.0,
    gorduras: 100.0,
    fibras: 0.0,
    medidasCaseiras: [
      { descricao: "1 colher de sobremesa", gramas: 5 },
      { descricao: "1 colher de sopa", gramas: 10 },
      { descricao: "2 colheres de sopa", gramas: 20 },
    ],
  },
  {
    id: "taco-29",
    nome: "Pasta de Amendoim Integral",
    categoria: "Gorduras & Óleos",
    porcaoPadraoGramas: 100,
    calorias: 588,
    proteinas: 25.0,
    carboidratos: 20.0,
    gorduras: 50.0,
    fibras: 8.0,
    medidasCaseiras: [
      { descricao: "1 colher de sopa rasa", gramas: 15 },
      { descricao: "1 colher de sopa cheia", gramas: 25 },
    ],
  },
  {
    id: "taco-30",
    nome: "Castanha-do-Pará / Castanha-do-Brasil",
    categoria: "Gorduras & Óleos",
    porcaoPadraoGramas: 100,
    calorias: 643,
    proteinas: 14.5,
    carboidratos: 15.1,
    gorduras: 63.5,
    fibras: 7.9,
    medidasCaseiras: [
      { descricao: "1 unidade", gramas: 4 },
      { descricao: "2 unidades", gramas: 8 },
      { descricao: "1 punhado (30g)", gramas: 30 },
    ],
  },
  {
    id: "taco-31",
    nome: "Semente de Chia / Linhaça",
    categoria: "Gorduras & Óleos",
    porcaoPadraoGramas: 100,
    calorias: 486,
    proteinas: 16.5,
    carboidratos: 42.1,
    gorduras: 30.7,
    fibras: 34.4,
    medidasCaseiras: [
      { descricao: "1 colher de sobremesa", gramas: 10 },
      { descricao: "1 colher de sopa cheia", gramas: 15 },
    ],
  },

  // --- SUPLEMENTOS & MODULADORES ---
  {
    id: "taco-32",
    nome: "Whey Protein Concentrado 80%",
    categoria: "Suplementos",
    porcaoPadraoGramas: 100,
    calorias: 400,
    proteinas: 80.0,
    carboidratos: 6.0,
    gorduras: 6.0,
    fibras: 0.0,
    medidasCaseiras: [
      { descricao: "1 scoop raso", gramas: 20 },
      { descricao: "1 scoop padrão (30g)", gramas: 30 },
      { descricao: "1 scoop e meio", gramas: 45 },
    ],
  },
  {
    id: "taco-33",
    nome: "Whey Protein Isolado 90%",
    categoria: "Suplementos",
    porcaoPadraoGramas: 100,
    calorias: 367,
    proteinas: 90.0,
    carboidratos: 1.0,
    gorduras: 0.8,
    fibras: 0.0,
    medidasCaseiras: [
      { descricao: "1 scoop padrão (30g)", gramas: 30 },
    ],
  },
  {
    id: "taco-34",
    nome: "Creatina Monohidratada",
    categoria: "Suplementos",
    porcaoPadraoGramas: 100,
    calorias: 0,
    proteinas: 0.0,
    carboidratos: 0.0,
    gorduras: 0.0,
    fibras: 0.0,
    medidasCaseiras: [
      { descricao: "1 dosador pequeno", gramas: 3 },
      { descricao: "1 dosador padrão", gramas: 5 },
    ],
  },

  // --- VERDURAS & LEGUMES ---
  {
    id: "taco-35",
    nome: "Brócolis, cozido no vapor",
    categoria: "Verduras & Legumes",
    porcaoPadraoGramas: 100,
    calorias: 25,
    proteinas: 2.1,
    carboidratos: 4.4,
    gorduras: 0.5,
    fibras: 3.4,
    medidasCaseiras: [
      { descricao: "1 pires de chá", gramas: 80 },
      { descricao: "1 prato de sobremesa", gramas: 150 },
    ],
  },
  {
    id: "taco-36",
    nome: "Alface Americana / Crespa, crua",
    categoria: "Verduras & Legumes",
    porcaoPadraoGramas: 100,
    calorias: 11,
    proteinas: 1.3,
    carboidratos: 1.7,
    gorduras: 0.2,
    fibras: 1.8,
    medidasCaseiras: [
      { descricao: "4 folhas médias", gramas: 40 },
      { descricao: "Prato raso à vontade", gramas: 100 },
    ],
  },
  {
    id: "taco-37",
    nome: "Tomate, com semente, fresco",
    categoria: "Verduras & Legumes",
    porcaoPadraoGramas: 100,
    calorias: 15,
    proteinas: 1.1,
    carboidratos: 3.1,
    gorduras: 0.2,
    fibras: 1.2,
    medidasCaseiras: [
      { descricao: "4 fatias médias", gramas: 60 },
      { descricao: "1 unidade média", gramas: 110 },
    ],
  },
  {
    id: "taco-38",
    nome: "Cenoura, cozida",
    categoria: "Verduras & Legumes",
    porcaoPadraoGramas: 100,
    calorias: 30,
    proteinas: 0.8,
    carboidratos: 6.7,
    gorduras: 0.2,
    fibras: 2.6,
    medidasCaseiras: [
      { descricao: "1 colher de sopa ralada/picada", gramas: 20 },
      { descricao: "1 pires de chá", gramas: 80 },
    ],
  }
];

export function calculatePortionMacros(food: FoodItemTACO, gramas: number) {
  const factor = gramas / 100;
  return {
    calorias: Math.round(food.calorias * factor),
    proteinas: Number((food.proteinas * factor).toFixed(1)),
    carboidratos: Number((food.carboidratos * factor).toFixed(1)),
    gorduras: Number((food.gorduras * factor).toFixed(1)),
    fibras: Number((food.fibras * factor).toFixed(1)),
  };
}

export function searchTACO(query: string, categoria?: string): FoodItemTACO[] {
  const q = query.trim().toLowerCase();
  return TACO_DATABASE.filter((item) => {
    const matchesQuery = !q || item.nome.toLowerCase().includes(q) || item.categoria.toLowerCase().includes(q);
    const matchesCat = !categoria || categoria === "Todos" || item.categoria === categoria;
    return matchesQuery && matchesCat;
  });
}
